name: s_mobills
description: Control your finances
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_hive_store: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_flavor: ^3.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.0.3
  get_it: ^7.7.0
  intl: ^0.18.1
  json_annotation: ^4.5.0
  path_provider: ^2.0.10
  shared_preferences: ^2.2.3

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/resources/fonts/Roboto-Black.ttf
        - asset: lib/resources/fonts/Roboto-BlackItalic.ttf
        - asset: lib/resources/fonts/Roboto-Bold.ttf
        - asset: lib/resources/fonts/Roboto-BoldItalic.ttf
        - asset: lib/resources/fonts/Roboto-Italic.ttf
        - asset: lib/resources/fonts/Roboto-Light.ttf
        - asset: lib/resources/fonts/Roboto-LightItalic.ttf
        - asset: lib/resources/fonts/Roboto-MediumItalic.ttf
        - asset: lib/resources/fonts/Roboto-Regular.ttf
        - asset: lib/resources/fonts/Roboto-Thin.ttf
        - asset: lib/resources/fonts/Roboto-ThinItalic.ttf
  uses-material-design: true
  generate: true
